can:
  interface: "canalystii"
  channel: 0
  bitrate: 1000000

motors:
  - id: 1
    limit_spd: 5.0
    limit_cur: 2.0
    offset_pos_1: 0.53 # initial position
    offset_pos_2: 0.7 # destination position
    control_mode: 0 
    speed:
      kp: 0.1
      ki: 0.05
      max_current: 12.0
      min_current: -12.0