can:
  interface: "canalystii"
  channel: 0
  bitrate: 1000000

motors:
  - id: 1
    limit_spd: 5.0
    limit_cur: 2.0
    control_mode: 0 
    speed:
      kp: 0.1
      ki: 0.05
      max_current: 12.0
      min_current: -12.0
  # - id: 2
  #   limit_spd: 6.0
  #   limit_cur: 2.5
  #   control_mode: 0     # Motor 2 ใช้ Current mode
  #   speed:
  #     kp: 0.1
  #     ki: 0.05
  #     max_current: 12.0
  #     min_current: -12.0
  # - id: 3
  #   limit_spd: 6.0
  #   limit_cur: 2.5
  #   control_mode: 0       # Motor 3 ใช้ Speed mode
  #   speed:
  #     kp: 0.25
  #     ki: 0.12
  #     max_speed: 32.0
  #     min_speed: -32.0
  # - id: 4
  #   limit_spd: 6.0
  #   limit_cur: 2.5
  #   control_mode: "position"    # Motor 4 ใช้ Position mode
  #   position:
  #     kp: 1.0
  #     kd: 0.2
  #     max_position: 12.56
  #     min_position: -12.56
